name: GITHUB_OUTPUT
run-name: Run by @${{ github.actor }}
on: push
jobs:
    share:
        name: Share GITHUB_OUTPUT
        runs-on: ubuntu-latest
        steps:
            - name: set-output
              id: source
              run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
            - env:
                  RESULT: ${{ steps.source.outputs.result }}
              run: echo "${RESULT}"


