name: Secret Variables
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        env:
            # githubに登録したSecretの値を取得する
            SECRET: ${{ secrets.PASSWORD }}
        steps:
            - run: echo "The password is ${SECRET}"
            - run: echo "${PASSWORD:0:3}" ${SECRET#?}