name: python test
run-name: python test run by ${{github.actor}}
on:
    push:
        branches:
            - main
        # python/test_project/以下にあるすべてのpyファイルを対象にする
        paths: [python/test_project/**/*.py]
    pull_request:
        branches:
            - main
jobs:
    python-test:
        runs-on: ubuntu-latest
        timeout-minutes: 3 # タイムアウトは必ず設定する
        defaults:
            run:
                working-directory: ./python/test_project
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Python 3.9
              uses: actions/setup-python@v5
              with:
                  python-version: 3.9
                  cache: pip
            - name: Install dependencies
              run: |
                 python -m pip install --upgrade pip 
                 python -m pip install -r requirements.txt
            - name: Run tests
              run: python -m pytest
