name: Variable
on: workflow_dispatch
jobs:
    run:
        runs-on: ubuntu-latest
        env:
            USERNAME: ${{vars.USERNAME}}
        steps:
            - run: echo "github registered username is ${USERNAME}"
